# This secret is used by the service broker
apiVersion: v1
kind: Secret
metadata:
  name: service-broker
  labels:
{{ include "mushop.labels" . | indent 4 }}
type: Opaque
data:
  {{ if eq .Values.global.mock.service "all" }}
  tenancy: {{ "mock" | b64enc }}
  user: {{ "mock" | b64enc }}
  fingerprint: {{ "mock" | b64enc }}
  region: {{ "mock" | b64enc }}
  passphrase: {{ "mock" | b64enc }}
  privatekey: {{ "mock" | b64enc }}
  {{ else }}
  tenancy: {{ required "Value .secrets.oci.tenantId is required!" .Values.secrets.oci.tenantId | b64enc }}
  user: {{ required "Value .secrets.oci.userId is required!" .Values.secrets.oci.userId | b64enc }}
  fingerprint: {{ required "Value .secrets.oci.fingerprint is required!" .Values.secrets.oci.fingerprint | b64enc }}
  region: {{ required "Value .secrets.oci.region is required!" .Values.secrets.oci.region | b64enc }}
  passphrase: {{ required "Value .secrets.oci.passphrase is required!" .Values.secrets.oci.passphrase | b64enc }}
  privatekey: |-
    {{ (.Files.Get "secrets/oci_api_key.pem") | b64enc }}
  {{ end }}
