apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-streams-secret
  labels:
{{ include "mushop.labels" . | indent 4 }}
type: Opaque
data:
  oci_compartment_id: {{ required "Value .secrets.oci.compartmentId is required!" .Values.secrets.oci.compartmentId | b64enc }}
  oci_tenant_id: {{ required "Value .secrets.oci.tenantId is required!" .Values.secrets.oci.tenantId | b64enc }}
  oci_user_id: {{ required "Value .secrets.oci.userId is required!" .Values.secrets.oci.userId | b64enc }}
  oci_fingerprint: {{ required "Value .secrets.oci.fingerprint is required!" .Values.secrets.oci.fingerprint | b64enc }}
  oci_region: {{ required "Value .secrets.oci.region is required!" .Values.secrets.oci.region | b64enc }}
  oci_api_key: {{ required "Value .secrets.oci.apiKey is required!" .Values.secrets.oci.apiKey | b64enc }}
