apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-streams-secret
  labels:
{{ include "mushop.labels" . | indent 4 }}
type: Opaque
data:
  {{ if eq .Values.global.mock.service "all" }}
  oci_compartment_id: {{ "mock" | b64enc }}
  oci_tenant_id: {{ "mock" | b64enc }}
  oci_user_id: {{ "mock" | b64enc }}
  oci_fingerprint: {{ "mock" | b64enc }}
  oci_region: {{ "mock" | b64enc }}
  oci_pass_phrase:  {{ "mock" | b64enc }}
  oci_api_key:  {{ "mock" | b64enc }}
  {{ else }}  
  oci_compartment_id: {{ required "Value .secrets.streams.compartmentId is required!" .Values.secrets.streams.compartmentId | b64enc }}
  oci_tenant_id: {{ required "Value .secrets.streams.tenantId is required!" .Values.secrets.streams.tenantId | b64enc }}
  oci_user_id: {{ required "Value .secrets.streams.userId is required!" .Values.secrets.streams.userId | b64enc }}
  oci_fingerprint: {{ required "Value .secrets.streams.fingerprint is required!" .Values.secrets.streams.fingerprint | b64enc }}
  oci_region: {{ required "Value .secrets.streams.region is required!" .Values.secrets.streams.region | b64enc }}
  oci_pass_phrase: {{ required "Value .secrets.streams.passphrase is required!" .Values.secrets.streams.passphrase | b64enc }}
  oci_api_key: |-
    {{ (.Files.Get "secrets/oci_streams_api_key.pem") | b64enc }}
  {{ end }}
