replicaCount: 1

image:
  repository: phx.ocir.io/intvravipati/mushop/orders
  tag: 1.0.2
  pullPolicy: Always

dbtools:
  repository: phx.ocir.io/intvravipati/mushop/dbtools
  tag: 1.0.1
  pullPolicy: IfNotPresent

osb: {}

secrets:
  oadbService:
  oadbUser:
  oadbPassword:
  oadbWalletPassword:

env:
  zipkin: zipkin.jaeger.svc.cluster.local
  javaOpts: -Xms128m -Xmx256m -XX:+UseG1GC -Dlogging.level.mushop.orders=TRACE  -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
  tnsAdmin: "/app/config"
service:
  port: 80
