dependencies:
  # Prometheus
  - name: prometheus
    version: 9.7.4
    condition: prometheus.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # Grafana
  - name: grafana
    version: 4.3.0
    condition: grafana.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # HPA Metrics
  - name: metrics-server
    version: 2.8.9
    condition: metrics-server.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # Ingress Controller
  - name: nginx-ingress
    version: 1.28.0
    condition: nginx-ingress.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # Service Catalog
  - name: catalog
    version: 0.2.1
    condition: catalog.enabled
    repository: https://svc-catalog-charts.storage.googleapis.com 

    ## TODO (peterj, 07/15/2019): OCI service broker should be here once they have a repo where the chart can be downloaded from