dependencies:
  # Prometheus
  - name: prometheus
    version: 11.1.2
    condition: prometheus.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # Grafana
  - name: grafana
    version: 5.0.13
    condition: grafana.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # HPA Metrics
  - name: metrics-server
    version: 2.11.1
    condition: metrics-server.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # Ingress Controller
  - name: nginx-ingress
    version: 1.36.3
    condition: nginx-ingress.enabled
    repository: https://kubernetes-charts.storage.googleapis.com
  # Service Catalog
  - name: catalog
    version: 0.3.0-beta.2
    condition: catalog.enabled
    repository: https://svc-catalog-charts.storage.googleapis.com 
