# https://github.com/helm/charts/blob/master/stable/metrics-server/README.md
metrics-server:
  enabled: true
  args: [
    # not recommended in production
    --kubelet-insecure-tls,
    --kubelet-preferred-address-types=InternalIP
  ]

# https://github.com/helm/charts/blob/master/stable/prometheus/README.md
prometheus:
  enabled: true

# https://github.com/helm/charts/blob/master/stable/grafana/README.md
grafana:
  enabled: true
  plugins: [ 'oci-datasource' ]
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
    dashboards:
      enabled: true
      label: grafana_dashboard

# https://github.com/kubernetes-sigs/service-catalog/blob/master/charts/catalog/README.md
catalog:
  enabled: true

# https://github.com/helm/charts/blob/master/stable/nginx-ingress/README.md
nginx-ingress:
  enabled: true

# https://github.com/jetstack/cert-manager/blob/master/README.md
cert-manager:
  enabled: true
  installCRDs: true
