version: '2'

services:
    carts:
        image: iad.ocir.io/cloudnative-devrel/micronaut-showcase/mushop/carts:1.0.0-SNAPSHOT
        hostname: carts
        restart: always
        read_only: true
        tmpfs:
        - /tmp:rw,noexec,nosuid
        environment:
            - ORACLECLOUD_ATP_OCID=ocid1.autonomousdatabase.oc1.iad.abuwcljsz4vwqssbgdihm334cjjv46xf4msw4yty6zrf4mmrvpxod7zgpaaq
            - ORACLECLOUD_ATP_WALLET_PASSWORD=Palko.123
            - ORACLECLOUD_ATP_USERNAME=micronaut
            - ORACLECLOUD_ATP_PASSWORD=R8SGn1g.3N4x
        ports:
            - "8080:80"

