replicaCount: 1

image:
  repository: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/fulfillment
  suffix: native
  tag: 2.0.0-SNAPSHOT
  pullPolicy: Always

osb: {}

env:
  natsHost: "nats"
  natsPort: 4222
  newOrdersSubject: mushop-orders
  shippedOrdersSubject: mushop-shipments

service:
  port: 80
