# Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

title: "MuShop App"
description: "Oracle Container Engine (OKE) stack for MuShop App"
schemaVersion: 1.1.0
version: "20190304"

logoUrl: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAACCCAYAAACKAxD9AAAACXBIWXMAAA7EAAAOxAGVKw4bAAARmUlEQVR42u2dfYxlZ13HPx5OrjeTyWYcx3VYJsOyrnVd1kWXdiW1lBWRFlpTebEI5UW0BowifxlCDDH9wxiChPgWowkxtBBpSVopi6lKCVlKKXVZgSzbsS7NMCzDZTqM4zCMN9fLqX883yf32dPzfs6dmTPzfJObO3PPvec853m+z+/t+T2/Ax4eHh4eHh4eHh4eHh4eHh7F8CNjPn9Q8vuRH5K9QYQg9nfo/B3kDH4EDBMI4clxdZ/OANcDc8BTwGPAet1+ChtsoB34IIMEQQYJ7HvkkCKNHE2iA0wDXWADWNvFJDgK3AzcAhwCrgBTwOeA5Z0iQhAb9NAhQlhRNRAjwjBGiKhhQkwAp4CfBw6oMx8HFnahJDoM/DrwduAaoA+cUDuXd4oIdsA7eiUNflCTZGGMFP0YGZoYqKPA+4AbRIpV4Czwx8CKI412GjPAbwJvA45Ial0REU4Cs3UvEFYcoK4IECbYBU3bGZEjbYbAQK9hA2R4A3Bc9zOUinizOvbdwKKutZPoAn8E3A7Myy74OPDfwF0JYzBWq97O/gmJ0AlHEgQpxmBQ45V0Hit9us7163RCIP0aApeA+yUNQuDlwD/ofXIHSdAB/hR4k0hwEfgb4K+c7zQitcISJOgmDH5RYpUZrCjDqAxj1x9IZVQ1JvvO7/5DRtcV4J2yG+4CPgz8k1TFdmJaUul2SagLwD3AfcBW0253WIAE7uwLCxAgqCGR4iSIUr4XJ0S/gqqIHCJ0RKqvaeAD6eSTwO9ICt4HLG0TCeaB10sSzKpd9wAPAj1JqbBJbyrMOWYlQZggBYKUQa1rJBYhReAcD5xjZcnwvw4ROpppXwH+TsdvFhmsNPy47IZozCS41TEML4sEZ3XtuEsejVMihI5NEOYEhChwvCopogKkscZrUlyiiGoYOhLP/vYrwAd1/NVy196h4x+VqzYOj2JW5HubjNhlRx0sp9z/2CRCHgmCHClgByZwrPwoh3CkfDfIUA9RjAwdfTYo0UFbjkT40dixy8CfAU/Ldz8stzISGXoNk2ESeK2udUqu7H3AXyrQlebCj0UiuO5hmBEVDFLeQ7H6V/X+Vc2uXorOPwZcJ9L9J3AuYSDTmO+qhzAhGFWEDK6N0E04vqKBWFK84RpZ8S8A/kLeRlN4p+yRY+qv+4H3ZJDtOeOSCGneQVESWJ/3MPCHzixdcogQP89L1QEb0r+PxAY4afZHGWToxIiQp162ElRD0ncelGh+v2brW+V6/q3IGzmz+lrp9udj1gPmFBBy3T0bEPqm+ueFMk4PAU+qLz5YUOI0LhHikcIyJHAHaVMzPFDHdDI8DauCBjGPJMhREWnHLBnyVFJcNbgqKqmjN4HzmqF3abBfod+c1MC+WH/POLGOrtOnLqzba1+T+t1l4GNSPRsFx65RIgQx97AKCez7RiwgkkWEtOBRlDObk8gQV2+DAlLBGouh084ohQwbmJW+9wPvAk4rNH1EhJrTjEbEWZOVvx7z+61LPg0clATtSBLcI5VQxE0di7EYJETq8ozCtEZtJQxKkKLjs8hRlQxhxjXTJIKrWvo53/9nzfQ+Zjn4hEh3RQGpJRl6T8vGSCPCjIjwk4pTfFUu4uUC7Q7GLRGygkVBgc+CDL0W5EiEKu5nGsGChBhDEgYJaqVfQCffr9+uy4Bck+r4gt43SngUgYiwWdILaTygFJcGZSRBkQGNryTmSYOyIi+NDGGBjt2KtalTIir5oIzbrojQrzgGkQhVZRI06j4GDc7OIGdwsz5P+j8qaDMUOXeUYSPgGK5lsJNJLI3aCEECIeqGjMMC6mAckch4m4tcYyumGrq0B42GmJuSBkXCzEHF9pTplLIE7ldUDbuNCI3OIBogQxlyBNvcYVkBpTZKhLBpiZDnzlUxfqIEV46EGEWekVmHLEU6J8lraIs0aFwiNDkz3aRTGGUzJbH5oIIqcb+4ybYUbW/UMtUQD6M3QoRxrK1b3TsHPDfmnnZEgtcpOmfbMUl28ktZiRSV/P64DNhxwfZxt4lJFI6hgYECKjZ+fkbBki9hFmp+EbPGvyr/2e4pOCXiTGAWeHo1ffOohFRoGxEi4Hv6e4YG8irDWKcFDTVyQw1cxixH/wFwpyOBzgEPS3XcgkkSnQc+hMnN+xgmZFtHNRVNUnEzpIctIcIQE4oeqn+nKBZAy5UIQxpKi44Fas4C3wWeJ5WwyWjpdcX57KJuZgX4uo6XzT9M0vsUJIEl6KAlRBhgciHsEvrzMQteS00QoUlbwdoE38HE3u2y9BYmGhc5hLmk2T8hVbFWY0CikvfSjfVBWVU0LXU267R/saJaO4pZt5hVm9YxO64uJcz0yLnOpH53tC4RooaJYBdROsCP6bPlFDFtZ+FKgjXchNeShwMOEQaSTkX77RjwEuAXRIZJ2T0LwBe5OjMrr7+uB27C5DnM6/yrUpOfZrTRNa5+L4g4xzG5EOeq9l+Y0IGd2AWrqIsp/c5m56xnGG9RipEXVSCBuwOqyI7qGed++xRf/JkDfhezF/EQo91XNvX/HCYT+sEccoX6/XuBGxktb0eYPIWXyLN6L2ZPZvxc/6LjR4EXiRRXqs5e21F9J8AS1ZAGoWZHIHbPxM6ZNNhRgjQoa/W7W+GKxhJcImwVJEIA/J5DghXgUcwmmAWd5wbgDr3nTZh3YbKduhLt54CHdK6hBvodmLyH+H2f1cBHkgpnmogs2oEYJAxSWbVgzzsP/ETCoA1TXkmivWiEsE+x9DQX85rFmyLBoMD9TWH2HczJ/nkfcJvI8TJMrsKqxPxNBc712yLjI8DvA7+ByWS+TeeyKfXHEtz9dXlfi7ITbqpLhMiRClV2DbkD1o0xfpLkugdJdRDKSqMoQZpB8UIbL1B7V+TdFOmvow7ZHwf+VVKgL719rwZm2omLpBmqh9RHAA/Ie9rSq4fZf9nXOQ45kVgXn5UreQCTNnekrkRw9Wy/olQYajYs6e9NRku9WeohStHrRQY0zdgtku51WJ28pnYXjZGsY3IMn+DqPZF2c8xTGsjVDOPN9k9PxLkQa8PAOZdNeUvyRBakHoYi1ck6XoOb/GHdqICr9zfEU8qDlNm5iUnHPiVv4YmMAS86eFEJQpcpu3OEUV2ElYJEWMbsRo5kzcfVyYoCYp93gj5pRFjCbKIZilj92LXWMPsnpmSHbCWcZx34tr47IRVRO8TskqIf87UDsncqB87s/CRmw8qqXknSoMmQdpWVOCturWooutt5A/j7HHvlbEFSrQJ/nSNh7y5wLtvPMwre1SaC25nDHDJkbUXrY3bwVpUAZaVEWPK81m2z3s1KQZ9/t2JTr1nH5qgcRwhSdK9N3nB3QFFgFkYpqiMq+buyUqHo969xVON32f76B03CelqVl/PDDBEfxELBA67eEhcWIESa8ZenHqIEgmZdx104KrrGcNSJ4NXJQt4NcDPFqUuEJDsh/m4DNkl1lIKcaGRUwL2L1zkYkrwDK60jymQ6P0/vqyVCy7sV01IJdl9lI0RII0WSiB9wdWm9eG3FIGWg0843TIgzuLuQ0ghhE14GFIu1B5jkmEAdt1VjEKacqN5DmEWiNOlyQmHjNXkcyxkDe608r/vkHmYFu35cv+kXjIcUJkKaqxjFvANXL8X3SAQZkiHJZhhmxAPipEhLv3c3wOYRYVbv6zWJcFARvTfpfEsZRDijyOEVSaE0IhwC3ohZjHqK7BXZUCQ4oHtZaloiRAXdMlc6BDFRTYa7OcyQEmlBoyQihAkqIs9WCNR5TRBhUoGpw8CvYHYyr6Zc85ckFWaALysqmSatXi6yzpOdS2lzP7u6jyfHqRqyrPogwbgragyW9RTipAtT1FARW8GGiTepl5CyoRluw882Myt+zhmRZVKD91P6ezOhXfMiQaQZntW+E/qutQ8WmggxZ3V+RPaScdJKYtbiUtFzpr1snKOvmWDD2UUWngInhtCvSYQVTD4mmLWFt4sQ8Qn3Hn3eESluwJTKibfrBkwNpVAkO59jzJ6SKlmVfbI+DomQNZuDFMOvqbzHNNJGOS5qmcgi1E/K2cCsCXxUdsKdMggfA/5LM/yX9VlXgxpoJn8I+DXMLuoAk9h7WoRax1RNyavVdJ2+f9Eh5LYQIY0QdQJCTZMjrx12HcWt0VgHPeAD0tVn5EXM6dyhyNAFPgP8o2bwHQpqvUKDb6XUBKMaSnfnxDeOMlrh7IkM206EpqXAuEmTp/rqYCAj7QOYVUSbNTSpYwuYIhoP6/gB6f6XyU08qDZckXj/PCZBpZdD5lNyX22hjqd2kghpBuS4Bi7I+V1UQaI1QeSBBm8J+HfHMBxIfz/qGH52kesSptSvzeJyE1aLLIu/UNJgBfgW+XWXxk6EOgNb59xByWtaleAuzHQalmiLjCqk5tkW5/WqijndzyI110pC2o0iq4xuZbNJuVoneHZtiDZiVve1XtVb2CtESJv1NsYwj8n3e6kG/5DjLcTrObfxPm06/iY110v2GhE6GvCbFeU7QfLimC2E1ZPrttzS+41q2GV7kghdBWJukb8+xyhxdk1+/pPAN7h6J9JA/2+0lAQ2eJZU1HNfEaEjq/s2uVIn5IrZcvuPY/ZSLsuYWtNrk73xGMEVkWGaiplJbSeCff7haUydhVvVET25cF+TC/c4o4zqvYhFSbYZrq73vC+I0JXovxETk79Rov2SSPBp+ewb7H18Q9LPVnAN9zDpn6UKTmJi8E8DPwT+B/gUJlQ7xf7C9ZjSvc9gNsNM75cbP43ZEfQDkeB7mGrpUy2OBdTBAXk9z2gynN4PN30rZrv5D/R6WFLgwD4lgbWV7pVU/CJm9XPP2ggTcg3/BLOq18fkBn6Y5K3i+wl2oWpDE+LQXiXChFzCd8tNXMNsP78Xs96/hce3HSI8t45o2c3ewXF5Bq/UoJ8FPkL6PsD9iJ5DhNm9JhHsTuXbgN/SZ49iHod7kfYUvdouItjHJ81UdSF3q0SYwCwW3SmXsYd5UPYlT4JnYUVECBk9u3vPqIbbMU9yPygSvJHsjSP7GRtOv3SouQl2N+Fa4DUyDhcVKDnP3lgbGBcRBs54Tu0FiTCBeQjmKYm7xzBFN7wkSMeW0z/hXlANISYD+EYZPReAT1AjIXOfwC0paJ8g11oi2FTuOxQU6WEih5/zKqEQ4s/IaC0R3MyiScwq4iPUzMPzaB8RpjGFJydl/Pwb9bJ7PVroNUxKGrxW7blbJPAG4j6TCPOYCKKtXvKANxBLj6FbLabfRiKEmFDyK3UTnyG70ITHs2H3VdoamWttJMKcYgbzcoMeYGefrtpWIkw4ruRqG4lwDFNFBKkDv6pYHlOM6l8Pq3paO0kE+/ALG0V8iOzaxR7JmJFEsPbBRtuIMAf8DGZhaUNqwZOgOhHij0lqDRGulUToYzagnPdEqIQjmDjMGjWe6bSTRHgxpmLICjWeReTBT0sqrGJK9bSKCLOMKpD1MBVC/JpCedjNPgckERbbRoTjjApe9jD7FD3Kwz7VpdNWIpxk9PS3JdpdIn+nEGhCueV5lttEhAD4OTF5GfOAD68WquE6Rlv/v0ONPR47QYRQEmFa0mDBj2flsTujflyo24/BDjT+hBofYnbpeCJUm0yHpRom2kiEEJOU2sUEkb5Fu5+cspPewqsZFeJ+oo6huFMS4Wd1Az1GFT88ymECs3TfwRQFuUzNNZqdIIItTL1MxZUyTwKukWQNMSl9i3UNbk+E9uEg8CrMquM6Zjv8lSYGZjtJMIGJhHkiVLex5jEPKAez72OBBsoEbScROhJptgycNxTLYw5TK+K4/v8IDQXjwm1ms638ZZ9n5NPVy03a64G3MHpu9Geb6sPtJEJfouzPMU8iu4CPKJbBPPAixQ82MSUCGqsXuZ1EGDJ6gPYmPjexLAbA9zHR2IuYRN/GXO/nbPPNPIOphPZ9fP5BWfwQ+D/gm5itgF9Wf3p4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHi0Ff8PIS+RFSylw7QAAAAASUVORK5CYII=

source:
  type: quickstart

locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region
    visible: false
  - title: "General Configuration"
    variables:
    - cluster_name
    - k8s_version
    - cluster_visibility
    visible: true
  - title: "Worker Nodes"
    variables:
    - node_pool_shape
    - num_pool_workers
    - node_pool_name
    visible: true
  - title: "Add Ons"
    variables:
    - cluster_options_add_ons_is_kubernetes_dashboard_enabled
    visible: true
  - title: "MuShop Features"
    variables:
    - mushop_mock_mode_all
    - mushop_atp
    - mushop_oss
    visible: true
  - title: "Advanced Options"
    variables:
    - show_advanced
    - generate_public_ssh_key
    - public_ssh_key
    - image_operating_system
    - image_operating_system_version
    - mock_mode_all
    visible: true
  - title: "Network Configuration"
    variables:
      - network_strategy 
      - vcn_id 
      - vcn_display_name 
      - vcn_cidr_block 
      - vcn_dns_label            
      - subnet_type 
      - subnet_span 
      - subnet_id 
      - subnet_display_name       
      - subnet_cidr_block      
      - subnet_dns_label
    visible:
      eq:
      - ${show_advanced}
      - Yes

  - title: "Extras Hidden"
    variables:
      - user_ocid
      - fingerprint
      - network_cidrs
      - cluster_options_admission_controller_options_is_pod_security_policy_enabled
    visible: false

  - title: "OCI Services Hidden"
    variables:
      - autonomous_database_cpu_core_count
      - autonomous_database_data_storage_size_in_tbs
      - autonomous_database_data_safe_status
      - autonomous_database_db_version
      - autonomous_database_license_model
      - autonomous_database_is_auto_scaling_enabled
      - autonomous_database_is_free_tier
      - autonomous_database_wallet_generate_type
      - db_admin_name
      - db_connection_name
      - db_wallet_name
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"
    required: true

  cluster_name:
    type: string
    title: "Cluster Name Prefix"
    description: "OKE cluster name prefix"
    required: true

  k8s_version:
    type: enum
    enum:
    - "v1.15.7"
    - "v1.14.8"
    title: "Kubernetes Version"
    default: "v1.15.7"
    description: "Kubernetes version installed on your master and worker nodes"
    required: true

  cluster_visibility:
    type: enum
    enum:
    - "Private"
    - "Public"
    title: "Choose visibility type"
    description: "The Kubernetes worker nodes that are created will be hosted in public or private subnet(s)"
    required: true

  node_pool_shape:
    type: oci:core:instanceshape:name
    title: "Worker Node Shape"
    description: "The shape for all nodes in the node pool."
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  num_pool_workers:
    type: integer
    title: "Number of Worker Nodes"
    description: "The number of worker nodes in the node pool."
    minimum: 1
    maximum: 1000
    required: true

  node_pool_name:
    visible: #($show_advanced  == ""Yes"")
      eq:
        - show_advanced 
        - "Yes"
    type: string
    title: "Node Pool Name"
    description: "Name of the node pool"
    required: true

  cluster_options_add_ons_is_kubernetes_dashboard_enabled:
    type: boolean
    title: "Kubernetes Dashboard Enabled"

  # Advanced Options
  show_advanced:
    type: enum
    enum:
    - "No"
    - "Yes"
    default: "No"
    title: "Open Advanced Options"
    required: true

  generate_public_ssh_key:
    visible: #($show_advanced  == ""Yes"")
      eq:
        - show_advanced 
        - "Yes"
    type: enum
    enum:
    - "No"
    - "Yes"
    default: "Yes"
    title: "Auto generate public ssh key?"
    required: true

  public_ssh_key:
    visible: #($show_advanced  == ""Yes"") + ($generate_public_ssh_key  == ""No"")
      eq:
        - generate_public_ssh_key 
        - "No"
        - show_advanced 
        - "Yes"
    type: string
    title: "Input SSH public key"
    description: "In order to access your private nodes with a public SSH key you will need to set up a bastion host (a.k.a. jump box)."
    required: false

  image_operating_system:
    visible: #($show_advanced  == ""Yes"")
      eq:
        - show_advanced 
        - "Yes"
    type: enum
    title: "Image OS"
    description: "The OS/image installed on all nodes in the node pool."
    enum:
      - "Oracle Linux"
    required: true

  image_operating_system_version:
    visible: #($show_advanced  == ""Yes"")
      eq:
        - show_advanced 
        - "Yes"
    type: string
    required: true
    title: "Image OS Version"
    description: "The OS/image version installed on all nodes in the node pool."    

  mushop_mock_mode_all:
    visible: yes
    type: boolean
    required: true
    title: "Enable Mock Mode"
    description: "Enable Mock Mode for MuShop all Services"

  # mushop_atp:
  #   visible: yes
  #   type: boolean
  #   default: true
  #   required: true
  #   title: "Deploy ATP for services"
  #   description: "Enable Oracle Autonomous Database ATP for all Services"

  # mushop_oss:
  #   visible: yes
  #   type: boolean
  #   default: true
  #   required: true
  #   title: "Deploy Streaming for services"
  #   description: "Enable Oracle Streaming for all Services"

  # Network Type Options
  network_strategy:
    type: enum
    title: Network Strategy
    description: Create or use existing Network Stack (VCN and Subnet)
    enum:
      - "Create New VCN and Subnet"
      # - "Use Existing VCN and Subnet"
    required: true
    default: "Create New VCN and Subnet"

  subnet_type:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy 
        - "Create New VCN and Subnet"
    type: enum
    title: Subnet Type
    description: Choose between private and public subnets
    enum:
      - "Private Subnet"
      - "Public Subnet"
    required: true
    default: "Public Subnet"

  vcn_id:
    visible: #($network_strategy  == "Use Existing VCN and Subnet")
      eq:
        - network_strategy 
        - "Use Existing VCN and Subnet"
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: compartment_ocid 
    required: true
    title: Existing Network
    description: An existing Virtual Cloud Network (VCN) in which to create the compute instances, network resources, and load balancers. If not specified, a new VCN is created.

  vcn_cidr_block:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy 
        - "Create New VCN and Subnet"
    type: string
    required: true
    default: 10.20.0.0/16
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: VCN CIDR BLOCK
    description: The CIDR of the new Virtual Cloud Network (VCN). If you plan to peer this VCN with another VCN, the VCNs must not have overlapping CIDRs.

  subnet_cidr_block:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy 
        - "Create New VCN and Subnet"
    type: string
    default: 10.20.10.0/24
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    required: true
    title: Subnet CIDR
    description: The CIDR of the new Subnet. The new subnet's CIDR should not overlap with any other subnet CIDRs.

outputGroups:
  - title: Mushop endpoints
    outputs:
      - mushop_url
      - grafana_url
      - external_ip
  - title: Passwords
    outputs:
      - db_password
  - title: Comments
    outputs:
      - comments
      - dev

outputs:
  mushop_url_button:
      type: link
      title: MuShop URL Button
      displayText: MuShop Storefront
  mushop_url:
    type: link
    title: MuShop
    displayText: Storefront
  grafana_url:
    type: link
    title: Grafana
    displayText: Dashboards
  db_password:
    type: string
    title: DB Password
    displayText: DB Pass
    sensitive: true
  comments:
    type: string
    title: Comments
    displayText: Comments
  dev:
    type: string
    title: dev
    displayText: dev note from A-Team
  
primaryOutputButton: mushop_url_button