apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalogue.fullname" . }}-connection
  labels: {{ include "catalogue.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.global.mock.service "all" }}
  oadb_service: {{ .Values.secrets.oadbService | default "mock" | b64enc }}
  oadb_user: {{ .Values.secrets.oadbUser | default "mock" | b64enc }}
  oadb_pw: {{ .Values.secrets.oadbPassword | default "mock" | b64enc }}
  {{- else }}
  oadb_service: {{ required "Value .secrets.oadbService is required!" .Values.secrets.oadbService | b64enc }}
  oadb_user: {{ required "Value .secrets.oadbUser is required!" .Values.secrets.oadbUser | b64enc }}
  oadb_pw: {{ required "Value .secrets.oadbPassword is required!" .Values.secrets.oadbPassword | b64enc }}
  {{- end }}