apiVersion: v1
kind: Service
metadata:
  name: {{ include "fulfillment.name" . }}
  labels: {{ include "fulfillment.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "fulfillment.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    run: {{ include "fulfillment.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
