apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orders.fullname" . }}
  labels: {{ include "orders.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/name: {{ include "orders.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "orders.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        mockmode: {{ .Values.global.mock.service | quote }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: /prometheus
        prometheus.io/port: "8082"
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount | default .Values.serviceAccount | default (printf "default") }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}-{{ .Values.global.cloud }}-{{ .Values.global.imageSuffix | default .Values.image.suffix }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              port: 8082
              path: /health/liveness
            initialDelaySeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              port: 8082
              path: /health/readiness
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 10
          env:
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts }}
            - name: NATS_HOST
              value: "{{ .Release.Name }}-{{ .Values.env.natsHost }}"
            - name: NATS_PORT
              value: "{{ .Values.env.natsPort }}"
            - name: ORDERS_NEW
              value: "{{ .Values.env.newOrdersSubject }}"
            - name: ORDERS_SHIPPED
              value: "{{ .Values.env.shippedOrdersSubject }}"
          {{- $cloud := .Values.cloud | default (.Values.global.cloud | default (printf "oci")) }}
          {{- if eq "oci" $cloud }}
            {{- include "orders.oadb.connection" . | nindent 12 }}
            {{- include "orders.oapm.connection" . | nindent 12 }}
            {{- include "orders.oims.config" . | nindent 12 }}
          {{- end }}
      nodeSelector:
          beta.kubernetes.io/os: linux
