apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: {{.Values.global.osb.name}}
  labels:
    "helm.sh/resource-policy": keep
{{ include "provision.labels" . | indent 4 }}
spec:
  url: http://{{ .Values.global.osb.name }}.{{ .Values.global.osb.namespace }}:{{ .Values.global.osb.port }}
