{{ if .Values.global.osb.atp }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ .Values.global.osb.instanceName }}-oadb-wallet-binding
  labels:
{{ include "provision.labels" . | indent 4 }}
spec:
  instanceRef:
    name: {{ .Values.global.osb.instanceName }}-atp
  parametersFrom:
    - secretKeyRef:
        name: {{ .Values.global.osb.instanceName}}-oadb-connection
        key: oadb_wallet_pw_osb
{{ end }}
