micronaut:
  application:
    name: catalogue
  server:
    thread-selection: io
  executors:
    io:
      n-threads: 75
      type: fixed
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/catalogue/images/**"
        paths: "classpath:images"
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false
    enabled: true
  data:
    pageable:
      default-page-size: -1
      sort-parameter-name: sort
      page-parameter-name: page
      size-parameter-name: size

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

flyway:
  datasources:
    default:
      locations: classpath:db/migration
      baseline-version: 0
      baseline-on-migrate: true