apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - secretName: mushop-tls-grafana
    hosts:
    - grafana.mushop.ateam.cloud
  rules:
  - host: grafana.mushop.ateam.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: mu-setup-grafana
          servicePort: 80