micronaut:
  application:
    name: user
  server:
    thread-selection: io
  executors:
    io:
      n-threads: 75
      type: fixed
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  prometheus:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

flyway:
  datasources:
    default:
      enabled: true
      baseline-version: 0
      baseline-on-migrate: true
