replicaCount: 1

image:
  repository: phx.ocir.io/intvravipati/mushop/user
  tag: 1.0.0
  pullPolicy: Always

secrets:
  oadbService: musers_tp
  oadbUser: musers_service
  oadbPassword:
  oadbAdminPassword:

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

securityContext:
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

service:
  port: 80
