replicaCount: 1

image:
  repository: phx.ocir.io/intvravipati/mushop/edge-router
  tag: 1
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 1000Mi
  requests:
    cpu: 50m
    memory: 256Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

service:
  port: 80
