{{ if .Values.global.osb.atp }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Values.global.osb.instanceName }}-atp
  labels:
{{ include "provision.labels" . | indent 4 }}
spec:
  clusterServiceClassExternalName: atp-service
  clusterServicePlanExternalName: standard
  parameters:
    name: {{ (printf "MuShop %s Db" (randAlphaNum 4)) | quote }}
    compartmentId: {{ required "Value .global.osb.compartmentId is required!" .Values.global.osb.compartmentId | quote }}
    cpuCount: 1
    storageSizeTBs: 1
    licenseType: BYOL
    autoScaling: false
  parametersFrom:
    - secretKeyRef:
        name: {{ .Values.global.osb.instanceName }}-oadb-admin
        key: oadb_admin_pw_osb
    - secretKeyRef:
        name: {{ .Values.global.osb.instanceName }}-oadb-connection
        key: oadb_db_osb
{{ end }}
{{ if .Values.global.osb.oss }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Values.global.osb.instanceName }}-oss
  labels:
{{ include "provision.labels" . | indent 4 }}
spec:
  clusterServiceClassExternalName: oss-service
  clusterServicePlanExternalName: standard
  parameters:
    name: {{ (printf "MuShop %s Streaming" (randAlphaNum 4)) | quote }}
    compartmentId: {{ required "Value .global.osb.compartmentId is required!" .Values.global.osb.compartmentId | quote }}
    partitions: 1
{{ end }}
{{ if .Values.global.osb.objectstorage }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Values.global.osb.instanceName }}-objectstorage
  labels:
{{ include "provision.labels" . | indent 4 }}
spec:
  clusterServiceClassExternalName: object-store-service
  clusterServicePlanExternalName: standard
  parameters:
    name: {{ (printf "MuShop %s Catalogue Bucket" (randAlphaNum 4)) | quote }}
    compartmentId: {{ required "Value .global.osb.compartmentId is required!" .Values.global.osb.compartmentId | quote }}
    namespace: ociateam
    publicAccessType: "ObjectReadWithoutList"
{{ end }}