title: "MuShop Always Free Quickstart Demo"
description: "A demo eCommerce example app using Always Free Oracle Cloud Infrastructure"
schemaVersion: 1.1.0
version: "20190304"

logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=63403497"

source:
  type: marketplace
  reference: 63403427

locale: "en"