title: "MuShop Always Free Quickstart Demo"
description: "A demo eCommerce example app using Always Free Oracle Cloud Infrastructure"
schemaVersion: 1.1.0
version: "20190304"

logoUrl: "https://cloudmarketplace.oracle.com/marketplace/content?contentId=63403497"

source:
  type: marketplace
  reference: 

locale: "en"
groupings:
  - title: "General Configuration"
    visible: false
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region
    - mp_listing_id
    - mp_listing_resource_id
    - mp_listing_resource_version

  - title: "MuShop Configuration"
    variables:
    - database_name
    - num_nodes
    - availability_domain
    - compute_shape

  - title: "Optional Configuration"
    variables:
    - ssh_public_key

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    # type: string
    required: true
    title: "MuShop Compartment"
    description: "The compartment in which to create MuShop instance(s)"

  availability_domain:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    default: 3
    title: "Availability Domain"
    description: "Availability Domain"

  compute_shape:
    type: oci:core:instanceshape:name
    default: "VM.Standard.E2.1.Micro"
    #type: string
    title: "Compute Shape"
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageId: ${mp_listing_resource_id}

  mp_listing_id:
    type: string    
    required: true    
    description: "Marketplace Listing ID"

  mp_listing_resource_id:
    type: oci:core:image:id
    required: true
    description: "Marketplace Image OCID"
    dependsOn:
      compartmentId: ${compartment_ocid} 

  mp_listing_resource_version:
    type: string
    required: true
    description: "Marketplace Listing package version"

outputGroups:
  - title: "Output Group"
    outputs:
      - ${instance_public_ip}
      - ${instance_id}

outputs:
  instance_public_url:
    type: link
    title: MuShop VM
    visible: false

  instance_public_ip:
    type: link
    title: Public IP
    visible: true
  
  autonomous_database_password:
    type: string
    title: "Database Password"
    displayText: "Autonomous Database Password"
    visible: true
  
  dev:
    type: string
    title: "Message"
    displayText: "Made with \u2764 by Oracle A-Team"
    visible: true
  
primaryOutputButton: ${instance_public_url}