# Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

title: "Three-tier web application using Always-Free resources"
description: "A demo eCommerce example app (MuShop Basic) using Always-Free Oracle Cloud Infrastructure"
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

groupings:
  - title: "Basic Hidden"
    visible: false
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region

  - title: "General Configuration"
    variables:
    - num_nodes

  - title: "Optional Configuration"
    variables:
    - autonomous_database_name
    - show_advanced
    - generate_public_ssh_key
    - public_ssh_key

  - title: "Encryption using OCI Vault (KMS)"
    variables:
    - use_encryption_from_oci_vault
    - create_new_encryption_key
    - encryption_key_id
    - create_vault_policies_for_group
    - user_admin_group_for_vault_policy

  - title: "Advanced Resource Options"
    variables:
    - use_only_always_free_elegible_resources
    - lb_shape
    - instance_shape
    - autonomous_database_is_free_tier

  - title: "Extras Hidden"
    variables:
      - user_ocid
      - fingerprint
      - private_key_path
      - autonomous_database_db_version
      - autonomous_database_license_model
      - autonomous_database_cpu_core_count
      - autonomous_database_data_storage_size_in_tbs
      - image_operating_system
      - image_operating_system_version
      - is_pv_encryption_in_transit_enabled
      - vault_display_name
      - vault_type
      - vault_key_display_name
      - vault_key_key_shape_algorithm
      - vault_key_key_shape_length
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"

  num_nodes:
    type: enum
    enum:
    - "1"
    - "2"
    title: "Node Count"
    description: "Choose the number of compute instances to deploy"
    default: "2"
    required: true

  autonomous_database_name:
    type: string
    title: "Database Name"
    description: "The name for the Autonomous Database instance"
    minLength: 1
    maxLength: 10
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    required: true

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options, allowing enable customer managed encryption keys, select your ssh key, and other advanced options. NOTE: Only encryption and ssh key changes are available as Always Free resources, other advanced options may not be available on the Always Free."
    visible: true

  generate_public_ssh_key:
    type: boolean
    title: "Auto-generate public ssh key?"
    description: "Auto-generate a public key and assign to the compute instances. Uncheck to provide your own public key or leave blank not to use any attach any key to the compute instance"
    required: true
    visible:
      and:
        - show_advanced

  public_ssh_key:
    type: oci:core:ssh:publickey
    required: false
    title: "SSH Public Key"
    description: "The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH"
    additionalProps:
      allowMultiple: true
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - generate_public_ssh_key

  use_encryption_from_oci_vault:
    type: boolean
    title: "Encrypt boot volume and object storage bucket with a key that you manage?"
    description: "By default, Oracle manages the keys that encrypt the boot volume and object storage bucket, but you can choose a key from a vault that you have access to if you want greater control over the key's lifecycle and how it's used."
    visible:
      and:
        - show_advanced

  create_new_encryption_key:
    type: boolean
    title: "Create new vault and encryption key?"
    description: "Creates new vault and key on OCI Vault/Key Management/KMS and assign to boot volume of compute and object storage bucket"
    visible:
      and:
        - show_advanced
        - use_encryption_from_oci_vault

  encryption_key_id:
    type: string
    title: "Existent master encryption key"
    description: "Use an existent master encryption key to encrypt boot volume and object storage bucket"
    visible:
      and:
        - and:
          - show_advanced
          - use_encryption_from_oci_vault
        - not:
          - create_new_encryption_key

  create_vault_policies_for_group:
    type: boolean
    title: "Create policies to manage vault and keys?"
    description: "Creates policies to manage vault and keys. If you are on the Administrators group or already have the policies for a compartment, this policy is not needed. If you do not have access to allow the policy, ask your administrator to include it for you."
    visible:
      and:
        - show_advanced
        - use_encryption_from_oci_vault
        - create_new_encryption_key

  user_admin_group_for_vault_policy:
    type: string
    title: "Specific your group to include the policy"
    description: "Identity Group to allow manage vault and keys."
    visible:
      and:
        - show_advanced
        - use_encryption_from_oci_vault
        - create_new_encryption_key
        - create_vault_policies_for_group

  use_only_always_free_elegible_resources:
    type: boolean
    title: "Use only always free eligible resources?"
    description: "*** Unchecking this may use options that are not included or supported by Always Free eligible resources"
    visible:
      and:
        - show_advanced

  lb_shape:
    type: enum
    enum:
    - "10Mbps-Micro"
    - "100Mbps"
    - "400Mbps"
    - "8000Mbps"
    title: "Select a shape for the load balancer"
    description: "A load balancer provides automated traffic distribution from one entry point to multiple servers in a backend set. The load balancer ensures that your services remain available by directing traffic only to healthy servers in the backend set."
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_elegible_resources

  instance_shape:
    type: oci:core:instanceshape:name
    title: "Select a shape for the compute instances"
    description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
    dependsOn:
      compartmentId: compartment_ocid
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_elegible_resources

  autonomous_database_is_free_tier:
    type: boolean
    title: "Use always free Autonomous Database?"
    description: "Uses Always Free Transaction Processing Autonomous Database. Unchecking this option will provision a regular 1 OCPU ATP instance with License."
    visible:
      and:
        - and:
          - show_advanced
        - not:
          - use_only_always_free_elegible_resources

outputGroups:
  - title: "MuShop App details"
    outputs:
      - lb_public_url
      - autonomous_database_password
      - generated_private_key_pem
      - deploy_id
      - dev
      - comments

outputs:
  lb_public_url:
    type: link
    title: Open
    visible: true
  
  autonomous_database_password:
    type: string
    title: "Database Admin Password"
    displayText: "Autonomous Database Admin Password"
    visible: true
  
  generated_private_key_pem:
    type: string
    title: "Generated Private Key for SSH Access"
    displayText: "Generated Private Key for ssh access to compute nodes"
    visible: true

  dev:
    type: string
    title: "Message"
    # displayText: "Made with \u2764 by Oracle"
    visible: true
  
  deploy_id:
    type: string
    title: "Deployment Id"
    visible: true

  mushop_basic_source_code:
    type: link
    title: "MuShop Basic source code"
    visible: true

  comments:
    type: string
    title: "Comments"
    displayText: "The application URL will be unavailable for a few minutes after provisioning, while the application is configured"
    visible: true
  
primaryOutputButton: ${lb_public_url}