{{- $usesOsb := (index (.Values.global | default .Values) "osb").atp | default .Values.osb.atp -}}
{{- if not $usesOsb }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-admin
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
type: Opaque
data:
  oadb_admin_pw: {{ .Values.secrets.oadbAdminPassword | default "" | b64enc | default ("" | quote) }}
{{- end }}