{{- $usesOsb := (index (.Values.global | default .Values) "osb").atp | default .Values.osb.atp -}}
{{- $oadbService := .Values.secrets.oadbService | default .Values.global.oadbService -}}
{{- $oadbUser := .Values.secrets.oadbUser | default (printf "%s_user" .Chart.Name) -}}
{{- $oadbPass := .Values.secrets.oadbPassword | default (printf "%s_default321#" .Chart.Name) -}}


{{/* ADMIN credentials */}}
{{- if not (or $usesOsb .Values.oadbAdminSecret .Values.global.oadbAdminSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-admin
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
type: Opaque
data:
  oadb_admin_pw: {{ .Values.secrets.oadbAdminPassword | default "" | b64enc | default ("" | quote) }}
{{- end }}


{{/* DB Connection */}}
{{- if not (or $usesOsb .Values.oadbConnectionSecret .Values.global.oadbConnectionSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-connection
  labels: {{ include (printf "%s.labels" .Chart.Name ) . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.global.mock.service "all" }}
  oadb_service: {{ "mock" | b64enc }}
  {{- else }}
  oadb_service: {{ required "Value .secrets.oadbService is required!" $oadbService | b64enc }}
  {{- end }}
{{- end }}


{{/* DB Schema Credentials */}}
{{- if not (or $usesOsb .Values.oadbUserSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-credentials
  labels: {{ include (printf "%s.labels" .Chart.Name ) . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.global.mock.service "all" }}
  oadb_user: {{ "mock" | b64enc }}
  oadb_pw: {{ "mock" | b64enc }}
  {{- else }}
  oadb_user: {{ $oadbUser | b64enc }}
  oadb_pw: {{ $oadbPass | b64enc }}
  {{- end }}
{{- end }}