apiVersion: v1
kind: Service
metadata:
  name: {{ include "user.fullname" . }}
  labels: {{ include "user.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "user.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
