replicaCount: 1

image:
  repository: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/orders
  suffix: native
  tag: 2.0.0-SNAPSHOT
  pullPolicy: Always

dbtools:
  repository: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/dbtools
  tag: 21.1.0
  pullPolicy: IfNotPresent

osb: {}

secrets:
  oadbId:
  oadbService:
  oadbUser:
  oadbPassword:
  oadbWalletPassword:

env:
  zipkin: zipkin.jaeger.svc.cluster.local
  javaOpts: -Xms32m -Xmx150m -XX:MaxRAM=150m -Djava.security.egd=file:/dev/urandom -Doracle.jdbc.fanEnabled=false -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Dlogging.level.mushop.orders=INFO -Dspring.zipkin.enabled=false
  natsHost: "nats"
  natsPort: 4222
  newOrdersSubject: mushop-orders
  shippedOrdersSubject: mushop-shipments
service:
  port: 80

rbac:
  create: true
