apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ship
  name: ship
  namespace: mushop
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ship
  template:
    metadata:
      labels:
        run: ship
    spec:
      imagePullSecrets:
        - name: ocirsecret        
      containers:
      - image: phx.ocir.io/intvravipati/mushop/shipping:0.0.1
        name: ship
        env:
         - name: TENANT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: tenant_id
         - name: USER_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: user_id
         - name: FINGERPRINT
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: fingerprint
         - name: OCI_API_KEY
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_api_key
         - name: REGION
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: region
         - name: COMPARTMENT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: compartment_id
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ship
  name: ship
  namespace: mushop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30123
  selector:
    run: ship
  type: NodePort
