replicaCount: 1

image:
  repository: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/events
  suffix: native
  tag: 2.0.0-SNAPSHOT
  pullPolicy: Always

# Applied only for AWS cloud. The init job creates the topics
initJob:
  image:
    repository: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/kafka
    tag: latest
    pullPolicy: Always
  auth:
    security:
      protocol: SSL
    ssl:
      truststore:
        location: /kafka.client.truststore.jks

osb: {}

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
service:
  port: 80
