micronaut:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: ${AWS_METRICS_NAMESPACE:micronaut_mushop}

  ssl:
    trust-store:
      path: /certs/rds-truststore.jks
      password: changeme

datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/mysql
      create-schemas: true
