micronaut:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: ${AWS_METRICS_NAMESPACE:micronaut_mushop}

datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/mysql
