micronaut:
  application:
    name: fulfillment
  server:
    port: 8099

mushop:
  messaging:
    host: ${nats.host:localhost}
    port: 4222
    subjects:
      orders: mushop-orders
      shipments: mushop-shipments
