version: '3'

services:
  user:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: mushop/user
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    volumes:
      - ./Wallet_Creds:/usr/lib/oracle/19.3/client64/lib/network/admin/:ro
    environment:
      - reschedule=on-node-failure
      - OADB_USER
      - OADB_PW
      - OADB_SERVICE
    ports:
      - '3000:3000'
