micronaut:
  application:
    name: payment
  metrics:
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

payment:
  decline:
    amount: 200

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
