apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: queuemaster
  name: queuemaster
  namespace: mushop
spec:
  replicas: 1
  selector:
    matchLabels:
      run: queuemaster
  template:
    metadata:
      labels:
        run: queuemaster
    spec:
      imagePullSecrets:
        - name: ocirsecret     
      containers:
      - image: phx.ocir.io/intvravipati/mushop/queuemaster:0.0.3
        name: queuemaster
        env:
         - name: OCI_TENANT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_tenant_id
         - name: OCI_USER_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_user_id
         - name: OCI_FINGERPRINT
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_fingerprint
         - name: OCI_API_KEY
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_api_key
         - name: OCI_REGION
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_region
         - name: OCI_COMPARTMENT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_compartment_id
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: queuemaster
  name: queuemaster
  namespace: mushop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    #nodePort: 30124
  selector:
    run: queuemaster
  type: NodePort
