# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: queuemaster
  name: queuemaster
  namespace: mushop
spec:
  replicas: 1
  selector:
    matchLabels:
      run: queuemaster
  template:
    metadata:
      labels:
        run: queuemaster
    spec:
      containers:
      - image: phx.ocir.io/intvravipati/mushop/queuemaster:0.0.1
        name: queuemaster
        env:
         - name: TENANT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: tenant_id
         - name: USER_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: user_id
         - name: FINGERPRINT
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: fingerprint
         - name: OCI_API_KEY
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_api_key
         - name: REGION
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: region
         - name: COMPARTMENT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: compartment_id
        ports:
        - containerPort: 8080
          protocol: TCP
---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: queuemaster
  name: queuemaster
  namespace: mushop
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30124
  selector:
    run: queuemaster
  type: NodePort
