replicaCount: 1

image:
  repository: phx.ocir.io/intvravipati/mushop/catalogue
  tag: 0.0.1
  pullPolicy: Always

secrets:
  oadbService: mcatalogue_tp
  oadbUser: catalogue_user
  oadbPassword:

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 200m
    memory: 128Mi

env:
  zipkin: zipkin.jaeger.svc.cluster.local

securityContext:
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

service:
  port: 80
