replicaCount: 1

image:
  repository: phx.ocir.io/intvravipati/mushop/catalogue
  tag: 1.1
  pullPolicy: Always

secrets:
  oadbService: mcatalogue_tp
  oadbUser: catalogue_user
  oadbPassword:

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

env:
  zipkin: zipkin.jaeger.svc.cluster.local

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

securityContext:
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

service:
  port: 80
