{{- $cloud := .Values.cloud | default (.Values.global.cloud | default (printf "oci")) }}
{{- if eq "aws" $cloud }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include (printf "%s.fullname" .Chart.Name) . }}-init
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
data: {{- (.Files.Glob "config/*").AsConfig | nindent 2 }}
{{/*  config/client.properties: |*/}}
{{/*    security.protocol={{ .Values.initJob.auth.security.protocol }}*/}}
{{/*    ssl.truststore.location={{ .Values.initJob.auth.ssl.truststore.location }}*/}}
{{- end }}