global:
  cloud: oci
  mock:
    service: "none"
  ociAuthSecret: oci-credentials        # OCI authentication credentials secret name
  ossConnectionSecret: oss-connection   # Previously created streaming secret name
  oadbAdminSecret: oadb-admin           # Name of DB Admin secret created separately
  oadbWalletSecret: oadb-wallet         # Name of wallet secret created separately
  oadbConnectionSecret: oadb-connection # Name of connection secret created separately
  oosBucketSecret: oos-bucket           # Object storage bucket secret name (optional)
  ociDeploymentConfigMap: oci-deployment  # Name of Deployment details config map

ingress:
  hosts: # Configure ingress to support host-specific routing
    # - yourname.mushop.com 

tags:
  atp: true                               # General flag to use Oracle Autonomous Database
  streaming: false                        # General flag to use Oracle Streaming Service

api:
  env:
    trackingEnabled:          # Flag that enables sending of tracking events to events service. If event service is not deployed set to "false".

carts:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbWalletPassword:   # Wallet password entered when downloading ATP connection Wallet
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

catalogue:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

orders:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbWalletPassword:   # Wallet password entered when downloading ATP connection Wallet
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

user:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available
 
secrets:
  streams:
    bootstrapServers:     # Stream pool bootstrap servers
    jaasConfig:           # Stream pool jaas config