global:
  ociAuthSecret: oci-credentials        # OCI authentication credentials secret name
  oadbAdminSecret: oadb-admin           # Name of DB Admin secret created earlier
  oadbWalletSecret: oadb-wallet         # Name of wallet secret created earlier
  oadbConnectionSecret: oadb-connection # Name of connection secret created earlier
  mock:
    service: "false"

ingress:
  enabled: true

api:
  env:
    mediaUrl:                 # Object Storage URL for catalog image assets
    newsletterSubscribeUrl:   # Newsletter subscription endpoint (https://[API_GATEWAY_URL]/newsletter/subscribe)

carts:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbWalletPassword:   # Wallet password entered when downloading ATP connection Wallet
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

catalogue:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

orders:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbWalletPassword:   # Wallet password entered when downloading ATP connection Wallet
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available

user:
  secrets:
    oadbAdminPassword:    # ADMIN password entered when provisioning ATP database
    oadbService:          # TNS Name displayed when the Wallet is downloaded an example would be `mushopdb_TP`
    oadbUser:             # can be changed as long as oadbAdminPassword is available
    oadbPassword:         # can be changed as long as oadbAdminPassword is available
 
secrets:
  streams:
    streamId:
    streamName:
    compartmentId: 