global:
  mock:
    service: "false"

ingress:
  enabled: true

  hosts:
    - mushop.ateam.cloud
    - insecure.mushop.ateam.cloud

  # Value can be either prod or staging
  # This controls the cluster issuer what's used in Ingress
  clusterIssuer: prod

  # Used for ACME registration (if TLS is set)
  email: "no-reply@ateam-oracle.com"

  # If TLS is provided, cert-manager needs to be installed.
  tls: true

secrets:
  streams:
    region:
    compartmentId:
    streamName:
    # future support
    streamId: