{{- $usesOsb := (index (.Values.global | default .Values) "osb").atp | default .Values.osb.atp -}}
{{- if or $usesOsb .Values.oadbAdminSecret .Values.global.oadbAdminSecret .Values.secrets.oadbAdminPassword  }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "catalogue.fullname" . }}-init-{{ .Release.Revision }}
  labels: {{ include "catalogue.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: {{ include "catalogue.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      initContainers:
        {{- include "catalogue.init.wallet" . | nindent 8 }}
      containers:
        - name: init
          image: "{{ .Values.dbtools.repository }}:{{ .Values.dbtools.tag }}"
          imagePullPolicy: {{ .Values.dbtools.pullPolicy }}
          command: ["/bin/sh","-c"]
          args:
            - sqlplus ADMIN/\"${ORACLECLOUD_ATP_ADMIN_PASSWORD}\"@${ORACLECLOUD_ATP_WALLET_SERVICE} @service.sql ${ORACLECLOUD_ATP_USERNAME^^} ${ORACLECLOUD_ATP_PASSWORD}
          env:
            {{- include "catalogue.oadb.connection" . | nindent 12 }}
            {{- include "catalogue.oadb.admin" . | nindent 12 }}
          volumeMounts:
            {{- include "catalogue.mount.wallet" . | nindent 12 }}
            {{- include "catalogue.mount.initdb" . | nindent 12 }}
      volumes: {{- include "catalogue.volumes" . | nindent 8 }}
{{- end }}