replicaCount: 1

image:
  repository: nats
  tag: 2.1.2
  pullPolicy: IfNotPresent

exporter: 
  repository: synadia/prometheus-nats-exporter
  tag: 0.6.2
  pullPolicy: IfNotPresent

osb: {}

service:
  port:
    client: 4222
    monitoring: 8222
    routes: 6222
