version: '3'

services:
  nats:
    image: nats:2.2
    hostname: nats
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
  fulfillment:
    image: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/fulfillment:1.0.0-SNAPSHOT
    restart: always
    read_only: true
    ports:
      - 8082
    tmpfs:
      - /tmp:rw,noexec,nosuid
    depends_on:
      - nats
    environment:
      - NATS_HOST=nats
      - NATS_PORT=4222
      - ORDERS_NEW=mushop-orders
      - ORDERS_SHIPPED=mushop-shipments
