---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge
  labels:
    name: edge
    layer: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: edge
        layer: client
    spec:
      containers:
      - name: edge
        image: phx.ocir.io/intvravipati/mushop/edge-router:1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          httpGet:
            path: /ping
            port: http
---
apiVersion: v1
kind: Service
metadata:
  name: edge
  labels:
    name: edge
    layer: client
spec:
  selector:
    name: edge
    layer: client
  ports:
  - port: 80
    targetPort: 8080