{{- if not .Values.osb.atp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-wallet
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
type: Opaque
data:
{{- $globWallet := .Files.Glob (printf "%s*/*" (.Values.secrets.oadbWallet | default "secrets/Wallet" | trimSuffix "/")) }}
{{- ($globWallet).AsSecrets | nindent 2 }}
{{- end }}