apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipping.fullname" . }}
  labels:
{{ include "shipping.labels" . | indent 4 }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "shipping.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    run: {{ include "shipping.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 80
