replicaCount: 1

image:
  repository: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/payment
  suffix: native
  tag: 2.0.0-SNAPSHOT
  pullPolicy: Always

decline:
  amount: 200

service:
  port: 80
