---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
    layer: client
  namespace: mushop
spec:
  selector:
    name: api
    layer: client
  ports:
  - port: 80
    targetPort: 3000
