---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
    layer: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
        layer: client
    spec:
      containers:
      - name: api
        image: phx.ocir.io/intvravipati/mushop/api:1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: SESSION_REDIS
          value: session
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
