apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carts
  labels:
    name: carts
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: carts
    spec:
      containers:
      - name: carts
        image: phx.ocir.io/intvravipati/mushop/carts:1.0.1
        ports:
         - containerPort: 80
        env:
        - name: ZIPKIN
          value: zipkin.jaeger.svc.cluster.local
        - name: JAVA_OPTS
          value: -Xms64m -Xmx128m -XX:+UseG1GC -Dlogging.level.mushop.carts=TRACE  -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
        - name: JDBC_URL
          value: "jdbc:oracle:thin:@db3_tp?TNS_ADMIN=./config"
        - name: OADB_USER
          valueFrom:
            secretKeyRef:
              name: atp-secret
              key: carts_oadb_user
        - name: OADB_PW
          valueFrom:
            secretKeyRef:
              name: atp-secret
              key: carts_oadb_pw
        - name: OADB_SERVICE
          valueFrom:
            secretKeyRef:
              name: atp-secret
              key: carts_oadb_service   
        - name: ATP_TRUST_PASS
          valueFrom:
          secretKeyRef:
              name: atp-secret
              key: carts_trust_pass 
        - name: ATP_KEY_PASS
          valueFrom:
          secretKeyRef:
              name: atp-secret
              key: carts_key_pass
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /app/config/keystore.jks
          subPath: keystore.jks
          name: wallet
          readOnly: true
        - mountPath: /app/config/truststore.jks
          subPath: truststore.jks
          name: wallet
          readOnly: true
        - mountPath: /app/config/tnsnames.ora
          subPath: tnsnames.ora
          name: wallet
          readOnly: true
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: wallet
          secret:
            secretName: carts-oadb-wallet
            defaultMode: 256
      nodeSelector:
        beta.kubernetes.io/os: linux