---
apiVersion: v1
kind: Service
metadata:
  name: session
  labels:
    name: session
    layer: client
  namespace: mushop
spec:
  ports:
  - port: 6379
  selector:
    name: session
    layer: client