---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: shipping
  name: shipping
  namespace: mushop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: shipping
  type: NodePort