---
apiVersion: v1
kind: Service
metadata:
  name: storefront
  labels:
    name: storefront
    layer: client
  namespace: mushop
spec:
  selector:
    name: storefront
    layer: client
  ports:
  - port: 80
    targetPort: 8080