apiVersion: v1
kind: Service
metadata:
  labels:
    run: stream
  name: stream
  annotations:
    prometheus.io/path: "/prometheus"
  namespace: mushop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    #nodePort: 30124
  selector:
    run: stream
  type: NodePort