apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: stream
  name: stream
spec:
  replicas: 1
  selector:
    matchLabels:
      run: stream
  template:
    metadata:
      labels:
        run: stream
    spec:
      containers:
      - image: phx.ocir.io/intvravipati/mushop/stream:1.0.0
        imagePullPolicy: Always
        name: stream
        env:
         - name: OCI_TENANT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_tenant_id
         - name: OCI_USER_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_user_id
         - name: OCI_FINGERPRINT
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_fingerprint
         - name: OCI_PASS_PHRASE
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_pass_phrase
              optional: true
         - name: OCI_API_KEY
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_api_key
         - name: OCI_REGION
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_region
         - name: OCI_COMPARTMENT_ID
           valueFrom:
             secretKeyRef:
              name: streams-secret
              key: oci_compartment_id
        ports:
        - containerPort: 80
          protocol: TCP