apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-router.fullname" . }}
  labels:
{{ include "edge-router.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "edge-router.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    layer: client
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
