datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.mushop-utilities.svc.cluster.local
      access: proxy
      isDefault: true
      disableDeletion: true
      editable: false
dashboards:
  default:
    cluster-metrics:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    pods:
      gnetId: 6336
      revision: 1
      datasource: Prometheus
sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
  dashboards:
    enabled: true
    label: grafana_dashboard
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
persistence:
  enabled: true
plugins:
  - oci-datasource