apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carts.fullname" . }}
  labels:
{{ include "carts.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "carts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "carts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ZIPKIN
              value: {{ .Values.env.zipkin }}
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts }}
            - name: TNS_ADMIN
              value: {{ .Values.env.tnsAdmin }}
            - name: OADB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}-connection
                  key: oadb_user
            - name: OADB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}-connection
                  key: oadb_pw
            - name: OADB_SERVICE
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}-connection
                  key: oadb_service
            - name: ATP_TRUST_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}-connection
                  key: oadb_wallet_pw
            - name: ATP_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}-connection
                  key: oadb_wallet_pw
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /app/config/keystore.jks
              subPath: keystore.jks
              name: wallet
              readOnly: true
            - mountPath: /app/config/truststore.jks
              subPath: truststore.jks
              name: wallet
              readOnly: true
            - mountPath: /app/config/tnsnames.ora
              subPath: tnsnames.ora
              name: wallet
              readOnly: true
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: wallet
          secret:
            secretName: {{ include "carts.fullname" . }}-wallet
            defaultMode: 256
      nodeSelector:
          beta.kubernetes.io/os: linux
