apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carts.fullname" . }}
  labels:
{{ include "carts.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "carts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "carts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ZIPKIN
              value: {{ .Values.env.zipkin }}
            - name: JAVA_OPTS
              value: {{ .Values.env.javaOpts }}
            - name: JDBC_URL
              value: {{ .Values.env.jdbcUrl }}
            - name: OADB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}
                  key: oadb_user
            - name: OADB_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}
                  key: oadb_pw
            - name: OADB_SERVICE
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}
                  key: oadb_service
            - name: ATP_TRUST_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}
                  key: trust_pass
            - name: ATP_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "carts.fullname" . }}
                  key: key_pass
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
          - name: tmp-volume
            emptyDir:
              medium: Memory
      nodeSelector:
          beta.kubernetes.io/os: linux
