apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carts.fullname" . }}-connection
  labels: {{ include "carts.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.global.mock.service "all" }}
  oadb_wallet_pw: {{ "mock" | b64enc }}
  oadb_service: {{ "mock" | b64enc }}
  oadb_user: {{ "mock" | b64enc }}
  oadb_pw: {{ "mock" | b64enc }}
  {{- else }}
  oadb_wallet_pw: {{ required "Value .secrets.oadbWalletPassword is required!" .Values.secrets.oadbWalletPassword | b64enc }}
  oadb_service: {{ required "Value .secrets.oadbService is required!" .Values.secrets.oadbService | b64enc }}
  oadb_user: {{ required "Value .secrets.oadbUser is required!" .Values.secrets.oadbUser | b64enc }}
  oadb_pw: {{ required "Value .secrets.oadbPassword is required!" .Values.secrets.oadbPassword | b64enc }}
  {{- end }}