apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carts.fullname" . }}
  labels:
{{ include "carts.labels" . | indent 4 }}
type: Opaque
data:
  oadb_pw: {{ required "Value .secrets.oadbPassword is required!" .Values.secrets.oadbPassword | b64enc }}
  oadb_service: {{ .Values.secrets.oadbService | b64enc }}
  oadb_user: {{ .Values.secrets.oadbUser | b64enc }}
  trust_pass: {{ required "Value .secrets.trustPass is required!" .Values.secrets.trustPass | b64enc }}
  key_pass: {{ required "Value .secrets.keyPass is required!" .Values.secrets.keyPass | b64enc }}