replicaCount: 1

image:
  repository: phx.ocir.io/oraclelabs/micronaut-showcase/mushop/api
  suffix: native
  tag: 2.0.0-SNAPSHOT
  pullPolicy: Always

env:
  trackingEnabled: false
  mediaUrl: /assets

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
service:
  port: 80
