replicaCount: 1

image:
  repository: phx.ocir.io/intvravipati/mushop/storefront
  tag: 1
  pullPolicy: Always

resources:
  limits:
    cpu: 300m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 300Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
  readOnlyRootFilesystem: true

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

service:
  port: 8080
