micronaut:
  application:
    name: api
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  security:
    authentication: session
    endpoints:
      logout:
        path: /api/logout
        get-allowed: true
      login:
        enabled: false
  http:
    client:
      follow-redirects: false
  session:
    http:
      redis:
        enabled: true
        namespace: 'mushop:sessions'
        write-mode: BACKGROUND
        enable-keyspace-events: false
redis:
    caches:
      discovery-client:
