micronaut:
  application:
    name: api
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  security:
    authentication: session
    endpoints:
      logout:
        path: /api/logout
        get-allowed: true
      login:
        enabled: false
  http:
    client:
      follow-redirects: false
  caches:
    discovery-client:
      enabled: false
