micronaut:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: ${AWS_METRICS_NAMESPACE:micronaut_mushop}
  session:
    http:
      redis:
        enabled: true

configuration:
  cloudProvider: AWS