micronaut:
  application:
    name: api
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  security:
    authentication: session
    intercept-url-map:
      - pattern: /api/swagger/*
        access:
          - isAnonymous()
      - pattern: /api/swagger-ui/*
        access:
          - isAnonymous()
    endpoints:
      logout:
        path: /api/logout
        get-allowed: true
      login:
        enabled: false
  http:
    client:
      follow-redirects: false
  caches:
    discovery-client:
      enabled: false
  router:
    static-resources:
      swagger:
        enabled: true
        paths: classpath:META-INF/swagger
        mapping: /api/swagger/**
      swagger-ui:
        enabled: true
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /api/swagger-ui/**
