{{- if not .Values.skip.streaming -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oss-connection
  labels: {{ include "mushop.labels" . | nindent 4 }}
type: Opaque
data:
  {{/* TODO: deprecate compartment/name as id/region should be all that is required */}}
  compartmentId: {{ required "Value .secrets.streams.compartmentId is required!" .Values.secrets.streams.compartmentId | b64enc }}
  streamName: {{ .Values.secrets.streams.streamName | default "" | b64enc | default ("" | quote) }}
  streamId: {{ .Values.secrets.streams.streamId | default "" | b64enc | default ("" | quote) }}
  region: {{ .Values.secrets.streams.region | default "" | b64enc | default ("" | quote) }}
{{ end }}