apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oss-connection
  labels: {{ include "mushop.labels" . | nindent 4 }}
type: Opaque
data:
  streamName:  {{ .Values.secrets.streams.streamName | default "" | b64enc }}
  streamId: {{ .Values.secrets.streams.streamId | default "" | b64enc }}