{{- if not .Values.skip.streaming -}}
apiVersion: v1
kind: Secret
metadata:
  {{/*
    OSS has very low service limits by default.
    The secret is deliberately not prefixed so
    that it may be provided separately altogether
  */}}
  name: streaming-secret
  labels: {{ include "mushop.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $keyFile := .Files.Get .Values.secrets.streams.keyFile }}
  {{- if ne .Values.global.mock.service "all" }}
  oci_compartment_id: {{ required "Value .secrets.streams.compartmentId is required!" .Values.secrets.streams.compartmentId | b64enc }}
  oci_tenant_id: {{ required "Value .secrets.streams.tenantId is required!" .Values.secrets.streams.tenantId | b64enc }}
  oci_user_id: {{ required "Value .secrets.streams.userId is required!" .Values.secrets.streams.userId | b64enc }}
  oci_fingerprint: {{ required "Value .secrets.streams.fingerprint is required!" .Values.secrets.streams.fingerprint | b64enc }}
  oci_region: {{ required "Value .secrets.streams.region is required!" .Values.secrets.streams.region | b64enc }}
  oci_pass_phrase: {{ .Values.secrets.streams.passphrase | default "" | b64enc | default ("" | quote) }}
  oci_api_key: |-
    {{ required (printf "API Key file %s is missing!" .Values.secrets.streams.keyFile) $keyFile | b64enc }}
  {{ end }}
{{- end }}