version: '2'

services:
    catalogue:
        build:
            context: .
            dockerfile: ./docker/catalogue/Dockerfile
        image: mushop/catalogue
        hostname: catalogue
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - reschedule=on-node-failure
            - OADB_USER=catalogue_user
            - OADB_PW=default_Password1
            - OADB_SERVICE=mcatalogue_tp
        ports:
            - "8080:80"

