---
apiVersion: autoscaling/v2beta1
# apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: storefront
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storefront
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
      # target:
      #   type: Utilization
      #   averageUtilization: 70