micronaut:
  application:
    name: carts
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false
      cloudwatch:
        enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

endpoints:
  prometheus:
    sensitive: false
    details-visible: ANONYMOUS
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
mongodb:
  uri: mongodb://${MONGO_USER:root}:${MONGO_PASS}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGODB:mongodb}?authSource=admin
