micronaut:
  metrics:
    export:
      oraclecloud:
        enabled: true
        namespace: ${ORACLECLOUD_METRICS_NAMESPACE:micronaut_mushop}
        resourceGroup: ${ORACLECLOUD_METRICS_RESOURCEGROUP:carts}
        compartmentId: ${ORACLECLOUD_METRICS_COMPARTMENT_ID}

oci:
  config:
    instance-principal:
      enabled: true

mongodb:
  uri: mongodb://${ORACLECLOUD_ATP_USERNAME}:${ORACLECLOUD_ATP_PASSWORD}@${ORACLECLOUD_ATP_HOST}:${ORACLECLOUD_ATP_PORT:27017}/${ORACLECLOUD_ATP_USERNAME}?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true

tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1
    http:
      url: ${ORACLECLOUD_TRACING_ZIPKIN_HTTP_URL}
      path: ${ORACLECLOUD_TRACING_ZIPKIN_HTTP_PATH}
    supportsJoin: false
