micronaut:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: ${AWS_METRICS_NAMESPACE:micronaut_mushop}

carts:
  database: mushop

mongodb:
  readPreference: PRIMARY
  ssl:
    enabled: true
  retry-writes: false

