{{- if ne .Values.global.mock.service "all" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stream.fullname" . }}
  labels:
{{ include "stream.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: {{ .Values.image.tag | quote }}
      app.kubernetes.io/name: {{ include "stream.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      run: {{ include "stream.name" . }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Values.image.tag | quote }}
        app.kubernetes.io/name: {{ include "stream.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        run: {{ include "stream.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
          env:
          {{- $credentialSecret := required "Value .ociAuthSecret is required!" (.Values.ociAuthSecret | default .Values.global.ociAuthSecret) }}
          {{- $streamSecret := .Values.global.ossStreamSecret | default (printf "%s-oss-connection" .Release.Name) }}
          - name: STREAM_ID
            valueFrom:
              secretKeyRef:
                name: {{ $streamSecret }}
                key: streamId
          - name: STREAM_NAME
            valueFrom:
              secretKeyRef:
                name: {{ $streamSecret }}
                key: streamName
          - name: OCI_COMPARTMENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ $streamSecret }}
                key: compartmentId
          - name: OCI_REGION
            valueFrom:
              secretKeyRef:
                name: {{ $streamSecret }}
                key: region
          # oci credentials
          - name: OCI_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: {{ $credentialSecret }}
                key: tenancy
          - name: OCI_USER_ID
            valueFrom:
              secretKeyRef:
                name: {{ $credentialSecret }}
                key: user
          - name: OCI_FINGERPRINT
            valueFrom:
              secretKeyRef:
                name: {{ $credentialSecret }}
                key: fingerprint
          - name: OCI_PASS_PHRASE
            valueFrom:
              secretKeyRef:
                name: {{ $credentialSecret }}
                key: passphrase
                optional: true
          - name: OCI_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $credentialSecret }}
                key: privatekey
{{- end -}}
