micronaut:
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

endpoints:
  prometheus:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

mongodb:
  uri: mongodb://${MONGO_USER:root}:${MONGO_PASS}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/?authSource=admin