global:
  secrets:
    oadbAdminPassword:
    oadbWallet:
    oadbWalletPassword:
    oadbService:
  mock:
    service: "false"

catalog:
  enabled: false

ingress:
  enabled: true

api:
  enabled: true

carts:
  enabled: true

catalogue:
  enabled: true

edge:
  enabled: true

orders:
  enabled: true

payment:
  enabled: true

session:
  enabled: true

shipping:
  enabled: true

storefront:
  enabled: true

stream:
  enabled: true

user:
  enabled: true

secrets:
  streams:
    compartmentId:
    tenantId:
    userId:
    region:
    fingerprint:
    passphrase:
    keyFile: secrets/oci_streams_api_key.pem
    streamName:
    # future support
    streamId:
  serviceBroker:
    tenantId:
    userId:
    region:
    fingerprint:
    passphrase:
    keyFile: secrets/oci_service_broker_api_key.pem