global:
  mock:
    service: "false"

hpa:
  enabled: true

ingress:
  enabled: true

  hosts:
    - mushop.ateam.cloud
    - insecure.mushop.ateam.cloud

  # Value can be either prod or staging
  # This controls the cluster issuer what's used in Ingress
  clusterIssuer: prod

  # Used for ACME registration (if TLS is set)
  email: "no-reply@ateam-oracle.com"

  tls:
    # Name of the secret where the cert will be stored for the host
    - secretName: mushop-ateam-cloud
      hosts:
        - mushop.ateam.cloud
        - insecure.mushop.ateam.cloud

api:
  enabled: true
  hpa:
    enabled: true
  env:
    mediaUrl: "https://objectstorage.us-phoenix-1.oraclecloud.com/n/intvravipati/b/mushop-images/o/"

carts:
  enabled: true

catalogue:
  enabled: true
  hpa:
    enabled: true

edge:
  enabled: true
  hpa:
    enabled: true
  service:
    port: 80

orders:
  enabled: true

payment:
  enabled: true

session:
  enabled: true

shipping:
  enabled: true

storefront:
  enabled: true
  hpa:
    enabled: true

stream:
  enabled: true

user:
  enabled: true
  hpa:
    enabled: true

secrets:
  streams:
    compartmentId:
    tenantId:
    userId:
    fingerprint:
    region:
    passphrase:
  serviceBroker:
    tenantId:
    userId:
    fingerprint:
    region:
    passphrase: