{{- if not .Values.osb.atp }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-admin
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
type: Opaque
data:
  oadb_admin_pw: {{ .Values.secrets.oadbAdminPassword | default "" | b64enc }}
{{- end }}