apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders.fullname" . }}
  labels:
{{ include "orders.labels" . | indent 4 }}
type: Opaque
data:
  oadb_pw: {{ required "Value .secrets.oadbPassword is required!" .Values.secrets.oadbPassword | b64enc }}
  oadb_service: {{ .Values.secrets.oadbService | b64enc }}
  oadb_user: {{ .Values.secrets.oadbUser | b64enc }}
  trust_pass: {{ required "Value .secrets.trustPass is required!" .Values.secrets.trustPass | b64enc }}
  key_pass: {{ required "Value .secrets.keyPass is required!" .Values.secrets.keyPass | b64enc }}
  oci_api_key: |-
    {{ (.Files.Get "secrets/oci_api_key.pem") | b64enc }}
  keystore.jks: |-
    {{ (.Files.Get "secrets/keystore.jks") | b64enc }}
  tnsnames.ora: |-
    {{ (.Files.Get "secrets/tnsnames.ora") | b64enc }}
  truststore.jks: |-
    {{ (.Files.Get "secrets/truststore.jks") | b64enc }}
