micronaut:
  application:
    name: payment
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
