micronaut:
  application:
    name: payment
  server:
    thread-selection: io
    executors:
      io:
        n-threads: 75
        type: fixed
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
      oraclecloud:
        enabled: false

payment:
  decline:
    amount: 100

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  prometheus:
    sensitive: false
    details-visible: ANONYMOUS
