name: Build and push Docker images

on:
  push:
    paths:
      # Match any VERSION file under /src folder
      - 'src/**/VERSION'
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and push the images
        run: |
            for versionFilePath in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep "VERSION");
            do
              # versionFilePath contains the full path to the VERSION file (e.g. src/api/VERSION)
              # we need to strip the "VERSION" from that to get the folder only
              folder=${versionFilePath%"/VERSION"}

              # Get the folder name and prefix it with "mushop"
              # E.g. "mushop-api", "mushop-fulfillment"
              IMAGE_NAME="mushop-$(cut -d "/" -f 2 <<< "$folder")"

              tmpTag="image-$RANDOM"
              docker build $folder --file $folder/Dockerfile --tag $tmpTag

              IMAGE_ID=${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.DOCKER_REPOSITORY }}/$IMAGE_NAME
              VERSION=$(cat $versionFilePath)

              echo IMAGE_ID=$IMAGE_ID
              echo VERSION=$VERSION

              docker tag $tmpTag $IMAGE_ID:$VERSION
              docker push $IMAGE_ID:$VERSION
            done;