# and edit them there. Note that it will be sync'ed to all the Micronaut repos
name: Java CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA: '11'
    strategy:
      matrix:
        application-path: [
            'api',
            'catalogue',
            'events',
            'fulfillment',
            'functions/newsletter-subscription',
            'orders',
            'payment',
            'user'
        ]
    steps:
      # https://github.com/actions/virtual-environments/issues/709
      - name: Free disk space
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA }}
      - name: Build with Gradle
        run: ./gradlew dependencyUpdates check -p $PROJECT_PATH --no-daemon --parallel --continue
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          PROJECT_PATH=${{ matrix.project-path }}
