name: Test Build Docs

on:
  pull_request:
    paths:
    - 'docs/**'
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build Hugo Docs
      run: |
          cd docs
          npm ci
          npm run build
          ls -al public
